### ISSUE TITLE
monit isn't running as PID 1

### ISSUE THREAD

**Issue by cpoole** [rawmind0/alpine-monit#1]
Hey rawmind0 it's me again :)

The entrypoint in this container is a bash script that creates monit as a child process.  I have a feeling this wasn't your intention.

currently ps -a of the alpine-traefik image outputs:

```
    1 root       0:00 /bin/bash -c /opt/monit/bin/monit-start.sh
   10 root       0:00 /opt/monit/bin/monit -I
   14 root       0:06 /opt/tools/confd/bin/confd -interval 15 -confdir /opt/tools/confd/etc -backend rancher -prefix /2015-12-19
   39 root       0:04 /opt/traefik/bin/traefik --configFile=/opt/traefik/etc/traefik.toml
  142 root       0:00 /bin/bash
  913 root       0:00 ps -a
```

but if you change the entrypoint to `ENTRYPOINT ["/opt/monit/bin/monit","-I"]` then the ps -a is as follows: 

```
bash-4.3# ps -a
PID   USER     TIME   COMMAND
    1 root       0:00 /opt/monit/bin/monit -I
    8 root       0:00 /opt/tools/confd/bin/confd -interval 15 -confdir /opt/tools/confd/etc -backend rancher -prefix /2015-12-19
   32 root       0:00 /opt/traefik/bin/traefik --configFile=/opt/traefik/etc/traefik.toml
   72 root       0:00 [traefik]
   77 root       0:00 /bin/bash
   84 root       0:00 ps -a
bash-4.3# 
```

Also please ignore the root user, im currently running these images as root so I can bind to privileged ports. maybe when I get more time ill add the kernel flags and seccomp profiles to bind as a non privileged user.

Sorry for all of the spam!

**Comment by rawmind0** [comment]
Hi @cpoole .... :)

Yes, i know how entrypoint works.... :P

If you review older version of the image, monit was launched as pid 1.  Unfortunately, monit doesn't seem to work well when it's running as pid 1. It lets zombie processes (as you can see in you "ps -a" output "72 root       0:00 [traefik]") , don't manage well app actions ,.... All this problems disappear if you don't run monit as pid 1, working as expected. A monit bug?? maybe...That's because monit is launched right now by a bash script.

Otherwise, if you put ENTRYPOINT ["/opt/monit/bin/monit","-I"], stdin, stdout and stderr are closed in the container. You couldn't redirect you app logs to them and you aren't able to see app logs through docker logs alpine-traefik or through rancher ui. If you want to try to run monit as pid 1, i recommend you that you try with ENTRYPOINT ["/opt/monit/bin/monit","-Iv"] . It lets stdin, stdout and stderr opened. :)

Best regards...

**Comment by cpoole** [comment]
ahhhh my apologies. I should have dug deeper. Thanks for the in depth explanation, I had never used monit until today. 

BTW thanks for your community work digging through your code has taught me a lot. I really like what you've done with confd and the rancher metadata service. I'll be heavily borrowing from that for a bunch of my new stuff. 

quick question if you don't mind: Why run confd and traefik in the same container? why not run them in separate containers and share a volume? I'm currently doing that and it's working pretty well so far.

**Comment by rawmind0** [comment]
Hi @cpoole,

thanks for your feedback. I'm so happy if this work helps you. :)

Your question is a good question....
As you say, you could run traefik and confd in a separate containers with a shared volume, without any problem. In that case would work ok, because traefik don't need to be restarted on configuration change.

Think about that, what happens if a configuration change needs a service restart?? If you are running in a separate containers, you couldn't tell confd to make a restar|reload of your service on configuration change. In fact, you could do it, but imho in a tricky and awful way, granting to the confd container the way to restart the service docker.

That's why i run the service and the confd from the same container. I code an "accumulative" monit configuration, that could read conf files from two paths, /opt/monit/etc/conf.d (local one) and /opt/tools/monit/conf.d (provided by rancher-tools) if exists. Then monit is able to start the service, and to start confd (or whatever you need) if you provide your custom /opt/tools . Then confd is able to restart the service on configuration change, imho, in a nicer way than sharing docker socket.

I think it's a matter of taste.... :P

**Comment by cpoole** [comment]
Thanks @rawmind0 for the response!

I totally agree with you, for a service that needs service restarts you definitely need an init system. You designed your system to work with many more services than just traefik. 

Also I added some features to your traefik container, I'll open up a pull request if you are interested in integrating any of them.
